### ISSUE TITLE
How many Spring Boots are there?

### ISSUE THREAD

**Issue by sokorototo** [shekelboi/SpringBootPractice#1]
Is this like a Ghosts of Christmas spirit kinda thing?

**Comment by shekelboi** [comment]
Hello, this question has already been addressed in PR [#15](https://youtu.be/dQw4w9WgXcQ).

**Comment by sokorototo** [comment]
> Hello, this question has already been addressed in PR [#15](https://youtu.be/dQw4w9WgXcQ).

Lord have mercy! I fell right into that one 😭

**Comment by shekelboi** [comment]
This fool actually fell for it 💀
